-- Felipe Config --
require("user.options")
require("user.keymaps")
require("user.plugins")

--vim.notify = require("notify")

require("user.colorscheme")
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.whichkey")
require("user.bufferline")
require("user.blankline")
require("user.lualine")
require("user.gitsigns")
require("user.toggleterm")
require("user.autopairs")
require("user.snippets")
require("user.vimtex")
require("user.dap")
require("user.dapui")
require("user.mason")
require("user.swenv")
require("user.neodev")
require("user.lean")
